CourseAllocation/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('MySite.urls')),
]

MySite/urls.py
from django.urls import path

from MySite import views
from MySite.views import HomeView, LoginView, RegisterView, DashboardView, DashboardAdminView

app_name = "MySite"

urlpatterns = [
    path("", HomeView.as_view(), name="home"),
    path("login", LoginView.as_view(), name="login"),
    path("register", RegisterView.as_view(), name="register"),
    path("logout", views.log_out, name="logout"),
    path("dashboard", DashboardView.as_view(), name="dashboard"),
    path("dashboard/admin", DashboardAdminView.as_view(), name="dash_admin"),
    path("dashboard/admin/choose_lecturer", views.choose_lecturer, name="choose_lecturer"),
    path("dashboard/admin/allocate-<int:course_id>-<str:staff_id>", views.allocate, name="allocate"),
    path("dashboard/admin/deallocate-<int:course_id>-<str:staff_id>", views.deallocate, name="deallocate"),
]

MySite/models.py
from django.contrib.auth.models import User
from django.db import models


# Create your models here.
class Department(models.Model):
    name = models.CharField(max_length=250)

    def __str__(self):
        return self.name


class Lecturer(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    last_name = models.CharField(max_length=50)
    first_name = models.CharField(max_length=50)
    email = models.EmailField()
    staff_id = models.CharField(max_length=20)
    department = models.ForeignKey(Department, on_delete=models.CASCADE)

    def __str__(self):
        return self.staff_id


class Course(models.Model):
    title = models.CharField(max_length=100)
    code = models.CharField(max_length=10)
    unit = models.IntegerField()
    department = models.ForeignKey(Department, on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.code}"


class CourseAllocation(models.Model):
    course = models.ForeignKey(Course, on_delete=models.CASCADE)
    lecturer = models.ForeignKey(Lecturer, on_delete=models.CASCADE)

MySite/views.py
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse
from django.utils.decorators import method_decorator
from django.views import View

from MySite.models import Lecturer, CourseAllocation, Department, Course


# Create your views here.
class LoginView(View):
    template_name = "mysite/login.html"

    def get(self, request):
        # Go to the login page
        return render(request, self.template_name)

    def post(self, request):
        # Check if form is submitting
        if request.method == "POST":
            # Collect inputs
            username = request.POST.get("staff_id").strip()
            password = request.POST.get("password")

            # Authenticate user
            user = authenticate(username=username, password=password)

            # Check if user exist
            if user is not None:
                # Login user
                login(request, user)
                # Redirect to learning page
                return HttpResponseRedirect(reverse("MySite:home"))
            else:
                # Send error message
                messages.error(request, "Invalid credentials")
                # Redirect to login page
                return HttpResponseRedirect(reverse("MySite:login"))


class RegisterView(View):
    template_name = "mysite/register.html"

    def get(self, request):
        departments = Department.objects.all()
        # Go to the register page
        return render(request, self.template_name, {"departments": departments})

    def post(self, request):
        # Check if form is submitting
        if request.method == "POST":
            # Get user input
            staff_id = request.POST.get('staff_id').strip().upper()
            last_name = request.POST.get('last_name').strip().upper()
            first_name = request.POST.get('first_name').strip().upper()
            email = request.POST.get('email').strip()
            department = request.POST.get('department').strip().upper()
            password = request.POST.get('password')
            confirm_password = request.POST.get('confirm_password')

            if not User.objects.filter(username=staff_id).exists() and Department.objects.filter(name__icontains=department).exists():
                if password == confirm_password:
                    user = User.objects.create_user(username=staff_id, password=password)
                    department = Department.objects.get(name__icontains=department)
                    Lecturer.objects.create(user=user, last_name=last_name, first_name=first_name, email=email,
                                            staff_id=staff_id, department=department)

                    messages.success(request, "Registration successful")
                    return HttpResponseRedirect(reverse("MySite:login"))
                else:
                    messages.success(request, "Password dos not match")
                    return HttpResponseRedirect(reverse("MySite:register"))
            else:
                messages.success(request, "User already exists")
                return HttpResponseRedirect(reverse("MySite:register"))


def log_out(request):
    logout(request)
    return HttpResponseRedirect(reverse("MySite:login"))


class HomeView(View):
    template_name = "mysite/home.html"

    def get(self, request):
        if Lecturer.objects.filter(staff_id=request.user.username).exists():
            lecturer = Lecturer.objects.get(user=request.user)
            return render(request, self.template_name, {"lecturer": lecturer})
        elif request.user.is_superuser:
            return render(request, self.template_name, {"admin": True})
        else:
            return render(request, self.template_name)


class DashboardView(View):
    template_name = "mysite/dashboard.html"

    @method_decorator(login_required)
    def get(self, request):
        if Lecturer.objects.filter(user=request.user).exists():
            lecturer = Lecturer.objects.get(user=request.user)
            alloc_courses = CourseAllocation.objects.filter(lecturer=lecturer)
            return render(request, self.template_name, {"lecturer": lecturer, "courses": alloc_courses})
        elif request.user.is_superuser:
            return HttpResponseRedirect('MySite:dash_admin')


class DashboardAdminView(View):
    template_name = "mysite/dash_admin.html"

    @method_decorator(login_required)
    def get(self, request):
        if not Lecturer.objects.filter(user=request.user).exists():
            departments = Department.objects.all()
            return render(request, self.template_name, {"departments": departments, "admin": True})
        else:
            return HttpResponseRedirect(reverse("MySite:dashboard"))

    def post(self, request):
        department = request.POST.get("department")
        all_lecturers = Lecturer.objects.filter(department=Department.objects.get(name=department))
        return render(request, self.template_name, {
            "current_dep": department,
            "lecturers": all_lecturers,
            "admin": True
        })


def choose_lecturer(request):
    template_name = "mysite/dash_admin.html"

    if request.method == "POST":
        staff_id = request.POST.get("lecturer")
        staff = Lecturer.objects.get(staff_id=staff_id)
        courses = Course.objects.filter(department=staff.department)
        unalloc_courses = []
        alloc_courses = []
        for course in courses:
            if CourseAllocation.objects.filter(**{"course": course, "lecturer": staff}).exists():
                alloc_course = CourseAllocation.objects.get(**{"course": course, "lecturer": staff})
                alloc_courses.append(alloc_course)

            if not CourseAllocation.objects.filter(course=course).exists():
                unalloc_courses.append(course)
        return render(request, template_name, {
            "staff": staff,
            "alloc_courses": alloc_courses,
            "unalloc_courses": unalloc_courses,
            "admin": True
        })


def allocate(request, course_id, staff_id):
    template_name = "mysite/dash_admin.html"
    staff = Lecturer.objects.get(staff_id=staff_id)
    course = Course.objects.get(id=course_id)
    if not CourseAllocation.objects.filter(**{"course": course, "lecturer": staff}).exists():
        CourseAllocation.objects.create(course=course, lecturer=staff)
    courses = Course.objects.filter(department=staff.department)
    unalloc_courses = []
    alloc_courses = []
    for c in courses:
        if CourseAllocation.objects.filter(**{"course": c, "lecturer": staff}).exists():
            cor = CourseAllocation.objects.get(**{"course": c, "lecturer": staff})
            alloc_courses.append(cor)
        if not CourseAllocation.objects.filter(course=c).exists():
            unalloc_courses.append(c)
    return render(request, template_name, {
        "staff": staff,
        "alloc_courses": alloc_courses,
        "unalloc_courses": unalloc_courses,
        "admin": True
    })


def deallocate(request, course_id, staff_id):
    template_name = "mysite/dash_admin.html"
    staff = Lecturer.objects.get(staff_id=staff_id)
    course = CourseAllocation.objects.get(id=course_id)
    course.delete()
    courses = Course.objects.filter(department=staff.department)
    unalloc_courses = []
    alloc_courses = []
    for course in courses:
        if CourseAllocation.objects.filter(**{"course": course, "lecturer": staff}).exists():
            course = CourseAllocation.objects.get(**{"course": course, "lecturer": staff})
            alloc_courses.append(course)
        if not CourseAllocation.objects.filter(course=course).exists():
            unalloc_courses.append(course)
    return render(request, template_name, {
        "staff": staff,
        "alloc_courses": alloc_courses,
        "unalloc_courses": unalloc_courses,
        "admin": True
    })

MySite/templates/mysite/dash_admin.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<section class="dashboard">
    <div class="container">
        {% if departments %}
        <h2>Select Department</h2>
        <form action="" method="post" style="margin-bottom:20px; padding: 10px">
            {% csrf_token %}
            <select name="department" style="width:100%; margin-bottom:20px; padding: 10px" required>
                <option value="">Select Department...</option>
                {% for dep in departments %}
                <option value="{{ dep.name }}">{{ dep.name }}</option>
                {% endfor %}
            </select>
            <button type="submit" style="margin: 0% 25%">Submit</button>
        </form>
        {% endif %}

        {% if current_dep %}
        <h2>Select Lecturer</h2>
        <p>Department: <b>{{ current_dep }}</b></p>
        <form action="{% url 'MySite:choose_lecturer' %}" method="post" style="margin-bottom:20px; padding: 10px">
            {% csrf_token %}
            <select name="lecturer" style="width:100%; margin-bottom:20px; padding: 10px" required>
                <option value="">Select Lecturer...</option>
                {% for lecturer in lecturers %}
                <option value="{{ lecturer.staff_id }}">{{ lecturer.last_name }} {{ lecturer.first_name }}</option>
                {% endfor %}
            </select>
            <button type="submit" style="margin: 0% 25%">Submit</button>
        </form>
        {% endif %}

        {% if staff %}
        <p>Lecturer: <b>{{ staff.last_name }} {{ staff.first_name }}</b></p>
        <p>Department: <b>{{ staff.department.name }}</b></p>
        <div class="courses">
            <h3>Unallocated Courses</h3>
            <table>
                <thead>
                <tr>
                    <th>Course Title</th>
                    <th>Course Code</th>
                    <th>Course Unit</th>
                    <th></th>
                </tr>
                </thead>
                <tbody>
                {% for course in unalloc_courses %}
                <tr>
                    <td>{{ course.title }}</td>
                    <td>{{ course.code }}</td>
                    <td>{{ course.unit }}</td>
                    <td><a href="{% url 'MySite:allocate' course.id staff.staff_id %}">Allocate</a></td>
                </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>

        <div class="courses">
            <h3>Allocated Courses</h3>
            <table>
                <thead>
                <tr>
                    <th>Course Title</th>
                    <th>Course Code</th>
                    <th>Course Unit</th>
                    <th>Lecturer</th>
                    <th></th>
                </tr>
                </thead>
                <tbody>
                {% for c in alloc_courses %}
                <tr>
                    <td>{{ c.course.title }}</td>
                    <td>{{ c.course.code }}</td>
                    <td>{{ c.course.unit }}</td>
                    <td>{{ c.lecturer.last_name }} {{ c.lecturer.first_name }}</td>
                    <td><a href="{% url 'MySite:deallocate' c.id staff.staff_id %}">Deallocate</a></td>
                </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
        {% endif %}

    </div>
</section>
{% endblock content %}

MySite/templates/mysite/dashboard.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<section class="dashboard">
    <div class="container">
        <h2>Dashboard</h2>

        <div class="courses">
            <h3>Your Courses</h3>
            <table>
                <thead>
                <tr>
                    <th>Course Code</th>
                    <th>Course Title</th>
                    <th>Course Unit</th>
                </tr>
                </thead>
                <tbody>
                {% for course in courses %}
                <tr>
                    <td>{{ course.course.title }}</td>
                    <td>{{ course.course.code }}</td>
                    <td>{{ course.course.unit }}</td>
                </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
</section>
{% endblock content %}

MySite/templates/mysite/home.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<section class="hero">
    <div class="hero-content">
        <h2>Welcome to Dominion University Ibadan</h2>
        <p>Course allocation plays a pivotal role in educational institutions, shaping the quality of education and
            student experience. Our institution understands the significance of a streamlined process for assigning
            courses to lecturers. With a meticulous approach, we ensure optimal utilization of faculty expertise while
            considering workload balance, institutional guidelines, and student demand. By prioritizing the best
            interests of both faculty and students, we strive to deliver a superior learning environment. Discover our
            commitment to efficient course allocation and empowering educators for academic excellence.</p>
        <p>Efficient course allocation is vital for educational institutions to provide high-quality education. The
            process involves assigning courses to lecturers based on their expertise, workload, and institutional
            requirements. By optimizing this allocation, institutions can enhance teaching standards and student
            learning experiences. Discover how course allocation benefits both lecturers and students, ensuring
            effective teaching and academic success.</p>
    </div>
</section>


{% endblock content %}

MySite/templates/mysite/login.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
  <section class="dashboard">
    <div class="container">
      <div class="login-form" style="padding: 20px">
        <h2>Login</h2>
        {% for msg in messages %}
        <p>{{ msg }}</p>
        {% endfor %}
        <form action="" method="post" style="margin-bottom:20px; padding: 10px">
          {% csrf_token %}
          <input type="text" name="staff_id" placeholder="Staff Id" required>
          <input type="password" name="password" placeholder="Password" required>
          <button type="submit" style="margin: 0% 25%">Login</button>
        </form>
        <p>Don't have an account? <a href="{% url 'MySite:register' %}">Register here</a></p>
      </div>
    </div>
  </section>
{% endblock content %}

MySite/templates/mysite/register.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
  <section class="dashboard">
    <div class="container">
      <div class="login-form" style="padding: 20px">
        <h2>Register</h2>
        {% for msg in messages %}
        <p>{{ msg }}</p>
        {% endfor %}
        <form action="" method="post" style="margin-bottom:20px; padding: 10px">
          {% csrf_token %}
          <input type="text" name="last_name" placeholder="Last Name" required>
          <input type="text" name="first_name" placeholder="First Name" required>
          <input type="text" name="staff_id" placeholder="Staff Id" required>
          <input type="email" name="email" placeholder="Email" required>
          <select name="department" id="" required style="width:100%; margin-bottom:20px; padding: 10px">
            <option value="">Select Option...</option>
            {% for dep in departments %}
            <option value="{{ dep.name }}">{{ dep.name }}</option>
            {% endfor %}
          </select><br>
          <input type="password" name="password" placeholder="Password" required>
          <input type="password" name="confirm_password" placeholder="Confirm Password" required>
          <button type="submit" style="margin: 0% 25%">Register</button>
        </form>
        <p>Already have an account? <a href="{% url 'MySite:login' %}">Login here</a></p>
      </div>
    </div>
  </section>
{% endblock content %}