CourseAllocation/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('MySite.urls')),
]

MySite/urls.py
from django.urls import path

from MySite import views
from MySite.views import HomeView, LoginView, RegisterView, DashboardView, DashboardAdminView

app_name = "MySite"

urlpatterns = [
    path("", HomeView.as_view(), name="home"),
    path("login", LoginView.as_view(), name="login"),
    path("register", RegisterView.as_view(), name="register"),
    path("logout", views.log_out, name="logout"),
    path("dashboard", DashboardView.as_view(), name="dashboard"),
    path("dashboard/admin", DashboardAdminView.as_view(), name="dash_admin"),
    path("dashboard/admin/choose_lecturer", views.choose_lecturer, name="choose_lecturer"),
    path("dashboard/admin/allocate-<int:course_id>-<str:staff_id>", views.allocate, name="allocate"),
    path("dashboard/admin/deallocate-<int:course_id>-<str:staff_id>", views.deallocate, name="deallocate"),
]

templates/base.html
<!DOCTYPE html>
<html lang="en">
{% load static %}
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Course Management</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'mysite/style.css' %}">
</head>
<body>
<header>
    <div class="logo">
        <!-- Place your logo here -->
        <img src="{% static 'images/logo.png' %}" width="50px" alt="Dominion University Logo">
    </div>
    <h1>DOMINION UNIVERSITY IBADAN</h1>
</header>

<nav>
    <ul class="nav-links">
        <li><a href="{% url 'MySite:home' %}">Home</a></li>
        {% if lecturer %}
        <li><a href="{% url 'MySite:dashboard' %}">Dashboard</a></li>
        <li><a href="{% url 'MySite:logout' %}">Logout</a></li>
        {% elif admin %}
        <li><a href="{% url 'MySite:dash_admin' %}">Allocate Course</a></li>
        <li><a href="{% url 'MySite:logout' %}">Logout</a></li>
        {% else %}
        <li><a href="{% url 'MySite:login' %}">Login</a></li>
        <li><a href="{% url 'MySite:register' %}">Register</a></li>
        {% endif %}
    </ul>
</nav>

{% block content %}
{% endblock content %}


<footer>
    <p>&copy; 2023 Dominion University Ibadan. All rights reserved.</p>
</footer>

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-geWF76RCwLtnZ8qwWowPQNguL3RmwHVBC9FhGdlKrxdiJJigb/j/68SIy3Te4Bkz"
        crossorigin="anonymous"></script>
<script src="{% static 'mysite/main.js' %}"></script>
</body>
</html>